package descansoApp;

import java.util.ArrayList;

public class BaseDatos {

    public static ArrayList<String> ciudades() {
        ArrayList<String> ret = new ArrayList<>();
        String texto;
        texto = "#nombre\n"
                + "Fray Bentos\n"
                + "\n"
                + "#des\n"
                + "Fray Bentos es una de las ciudades más bonitas del litoral uruguayo. Al situarse sobre la costa del Río Uruguay, en el límite con Argentina, es uno de los principales puntos de tránsito entre ambos países, a través del puente binacional. La ciudad tiene un importante puerto de aguas profundas y alberga uno de los balnearios fluviales más concurridos del país: Las Cañas. \n"
                + "\n"
                + "#info\n"
                + "\n"
                + "Conocida como \"romance de sol, barranca y río\", Fray Bentos fue concebida como una ciudad fluvial y como una vía abierta al movimiento turístico-comercial gracias a su ubicación a la vera del río Uruguay. Capital del departamento de Río Negro, es una auténtica ciudad puerto que aún conserva su carácter natural con aguas lo suficientemente profundas como para albergar embarcaciones de gran calado.\n"
                + "\n"
                + "Para llegar a Fray Bentos desde cualquier punto del Uruguay se pueden utilizar tres rutas nacionales: la n°2, que la une con el Litoral oeste; la n°3, que atraviesa todo el país como una columna vertebral; y la unión de estas con la ruta n°24, que nos la acercan desde cualquier destino. Además, esta hermosa ciudad uruguaya está unida a la República Argentina a través del puente internacional Libertador General San Martín, que la conecta con la ciudad de Gualeguaychú.\n"
                + "\n"
                + "El clima en esta región es del tipo templado-húmedo, con temperaturas que oscilan entre los 17° y los 20°C durante el verano y descienden considerablemente durante el período invernal.\n"
                + "\n"
                + "Fray Bentos invita a sus visitantes a disfrutar de paseos por la rambla y del contacto permanente con la naturaleza y el río. A 8 kilómetros de la ciudad se encuentra el balneario Las Cañas, donde es posible descansar sobre playas de arenas finas o bien realizar deportes náuticos y pesca deportiva.\n"
                + "\n"
                + "En las inmediaciones de la ciudad se halla el Barrio Anglo, declarado Monumento Histórico Nacional, donde se levanta un conjunto de más de 100 viviendas de fines del siglo XIX con reminiscencias inglesas y alemanas que rodea el ex-frigorífico Anglo. Vale la pena visitar el museo que allí funciona.\n"
                + "\n"
                + "El teatro Young, las plazas Constitución y Artigas, el anfiteatro público y el museo Solari son otros sitios de interés que abren sus puertas a la mirada curiosa de los turistas.\n"
                + "En los últimos tiempos, Fray Bentos ha tenido un gran crecimiento demográfico y económico producido por la instalación de la planta de celulosa finlandesa Botnia a escasos kilómetros de la ciudad.\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/fraybentos1.jpg\n"
                + "/descansoApp/baseDatos/fraybentos2.jpg\n"
                + "/descansoApp/baseDatos/fraybentos3.jpg\n"
                + "/descansoApp/baseDatos/fraybentos4.jpg\n"
                + "/descansoApp/baseDatos/fraybentos5.jpg\n"
                + "/descansoApp/baseDatos/fraybentos6.jpg\n"
                + "/descansoApp/baseDatos/fraybentos7.jpg\n"
                + "\n";

        ret.add(texto);
        return ret;
    }

    public static String comerciosActividades() {
        String texto;
        texto = "#nombre\n"
                + "Gran Hotel Fray Bentos\n"
                + "\n"
                + "#detalles\n"
                + "El descanso, la diversión y las actividades de negocios se dan la mano en este hotel que sorprende por la estética exterior clásica en contraste con el diseño minimalista e innovador de su interior. \n"
                + "Con los atardeceres sobre el Río Uruguay como marco, el hotel cuenta con piscina, sauna, gimnasio y estacionamiento privado. 64 habitaciones, equipadas con sommier, aire acondicionado individual frío-calor, minibar y TV Cable, disponen, también, de conexión a Internet de alta velocidad. Además, las áreas públicas permiten trabajar libremente a través de la conexión wireless. \n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Hotel\n"
                + "\n"
                + "#horario\n"
                + "Todos los días\n"
                + "\n"
                + "#ubicacion\n"
                + "Paraguay 3272 \n"
                + "\n"
                + "#telefono \n"
                + "4562-0566\n"
                + "\n"
                + "#web\n"
                + "www.granh.com/fray_bentos/\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/hotelg1.jpg\n"
                + "/descansoApp/baseDatos/hotelg2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Hotel RR\n"
                + "\n"
                + "#detalles\n"
                + "A solo 5 minutos del Centro de Fray Bentos se encuentra el Hotel RR, rodeado de extensos jardines, los cuales se aprecian desde las 10 habitaciones cada una con baño privado, T.V cable, aire acondicionado, es el lugar ideal para relajarse y descansar.\n"
                + "El hotel cuenta con desayuno continental, lavanderia y estacionamiento gratuito.\n"
                + "Por su ubicacion es ideal para descanso y relajacion.\n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Hotel\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Ruta Puente Puerto KM 309\n"
                + "\n"
                + "#telefono \n"
                + "4562-2728\n"
                + "\n"
                + "#web\n"
                + "www.despegar.com.uy/hoteles/h-352149/hotel-rr-fray+bentos\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/hotelr1.jpg\n"
                + "/descansoApp/baseDatos/hotelr2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Posada del Barranco\n"
                + "\n"
                + "#detalles\n"
                + "La Posada del Barranco se encuentra en el Balneario Las Cañas a 8 Km al Sur de Fray Bentos y a 100 metros del río Uruguay.\n"
                + "Construida sobre una de las tantas barrancas típicas del lugar de cara al río, la Posada ofrece habitaciones y apartametos con vistas panorámicas al río Uruguay.\n"
                + "Los Apart de la Posada del Barranco están equipados con TV por cable, frigobar, microondas, baño privado y balcón.\n"
                + "La posada cuenta con 6 habitaciones.\n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Posada\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Calle 10 e/ 11 y 12 - Las Cañas\n"
                + "\n"
                + "#telefono \n"
                + "4562-2874\n"
                + "\n"
                + "#web\n"
                + "www.posadadelbarranco.com.uy\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/posadab1.jpg\n"
                + "/descansoApp/baseDatos/posadab2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Brothers\n"
                + "\n"
                + "#detalles\n"
                + "Es la única parrillada del balneario, se puede comer además de asado, chorizos y todo lo de la parrilla, una muy buena piza hecha en su horno a leña,  chivitos y todas las minutas. Es una empresa familiar atendida por sus dueños y empleados que suman unas nueve personas por turno.\n"
                + "#tipo\n"
                + "estGastronomico\n"
                + "\n"
                + "#categoria\n"
                + "Restaurante\n"
                + "\n"
                + "#horario\n"
                + "Lunes a Viernes de 10:00 a 16:00 - Sabados y Domingo de 19:00 a 0:00\n"
                + "\n"
                + "#ubicacion\n"
                + "Las Cañas\n"
                + "\n"
                + "#telefono \n"
                + "4562-2565\n"
                + "\n"
                + "#web\n"
                + "www.xn--lascaas-8za.com/paradores.html\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/restaurantb1.jpg\n"
                + "/descansoApp/baseDatos/restaurantb2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "La Juventud\n"
                + "\n"
                + "#detalles\n"
                + "Gran lugar de reuniones familiares para deleitarse con un banquete especial que ofrece la carta dia a dia. El restaurante la Juventud ofrece un vario menu de comidas rapidas, caseras y de una parrilla inolvidable. Cituado en el centro de la ciudad de Fray Bentos.\n"
                + "\n"
                + "#tipo\n"
                + "estGastronomico\n"
                + "\n"
                + "#categoria\n"
                + "Restaurante\n"
                + "\n"
                + "#horario\n"
                + "Lunes a Sabados de 16:00 a 19.30 y Domingo de 8:00 a 17:00\n"
                + "\n"
                + "#ubicacion\n"
                + "18 de julio 1130 c/ Treinta y tres\n"
                + "\n"
                + "#telefono \n"
                + "4562-5840\n"
                + "\n"
                + "#web\n"
                + "www.facebook.com/RestaurantLaJuventud\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/restaurantj1.jpg\n"
                + "/descansoApp/baseDatos/restaurantj2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Pizzeria 33\n"
                + "\n"
                + "#detalles\n"
                + "Pizzería y Parrilada 33, ubicado en 33 Orientales casi Rincón de la Ciudad de Fray Bentos.\n"
                + "Pedidos a domicilio, sin cargo al Tel 45628617.\n"
                + "Variedad en Pizzas, Sándwiches Calientes, Hamburguesas, Chivitos y Parrilla.\n"
                + "\n"
                + "#tipo\n"
                + "estGastronomico\n"
                + "\n"
                + "#categoria\n"
                + "Pizzeria\n"
                + "\n"
                + "#horario\n"
                + "Lunes a Domingos  20:00 a 23:00 \n"
                + "\n"
                + "#ubicacion\n"
                + "33 orientales c/ Rincón\n"
                + "\n"
                + "#telefono \n"
                + "4562-8617\n"
                + "\n"
                + "#web\n"
                + "www.facebook.com/pages/Pizzeria-y-Parrillada-33/358073217638639\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/pizzeria331.jpg\n"
                + "/descansoApp/baseDatos/pizzeria332.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Museo de la Revolución Industrial\n"
                + "\n"
                + "#detalles\n"
                + "Cuando la Liebig Extract of Meat Co. se creó en Fray Bentos, una nueva etapa llegó a la región en cuanto al aprovechamiento de los recursos agropecuarios: había nacido la revolución industrial en el Río de la Plata. Era el año 1865 y la fábrica instalada a la vera del río Uruguay era uno de los establecimientos más importantes del mundo. \n"
                + "\n"
                + "La región tuvo un notable crecimiento, se edificaron las viviendas del barrio Anglo –denominado así porque dichas viviendas estaban destinadas a los operarios de la fábrica que pertenecía a capitales alemanes e ingleses–, llegó la energía eléctrica incluso 3 años antes que a Montevideo y en el resto del planeta ya se comentaba sobre la excelencia de los productos que allí se elaboraban, sobre todo del extracto de carne.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Museo\n"
                + "\n"
                + "#horario\n"
                + "Lunes a Viernes de 10:00 a 18:00\n"
                + "\n"
                + "#ubicacion\n"
                + "Anglo\n"
                + "\n"
                + "#telefono \n"
                + "4562-8481\n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/museo-de-la-revolucion-industrial1\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/museor1.jpg\n"
                + "/descansoApp/baseDatos/museor2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Rambla\n"
                + "\n"
                + "#detalles\n"
                + "El paseo es muy fácil de efectuar. Se puede comenzar por el borde norte, donde se encuentra el Parque Roosevelt, para luego ir por el contorno el río con dirección sur hasta confluir con el camino que conduce al Barrio Anglo, en el puente sobre el arroyo Laureles.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Paseos\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Cerca del Teatro de Verano\n"
                + "\n"
                + "#telefono \n"
                + " -\n"
                + "\n"
                + "#web\n"
                + "www.welcomeuruguay.com/fraybentos/rambla-fray-bentos.html\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/rambla1.jpg\n"
                + "/descansoApp/baseDatos/rambla2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Playas de las Cañas\n"
                + "\n"
                + "#detalles\n"
                + "Tan sólo ocho kilómetros al sur de Fray Bentos encontramos el balneario Las Cañas. Este bello paraje natural, ubicado entre puntas barrancosas y el tupido monte nativo, a la vera del río Uruguay, es el sitio ideal para disfrutar de las bondades del verano en un clima de relax y sosiego. \n"
                + "\n"
                + "Todos los años, cientos de personas se dan cita en Las Cañas para sentir el sol sobre las arenas blancas de sus playas. En los alrededores, un paraíso de ceibos, arrayanes, espinillos y sarandíes forman cerradas y tupidas galerías que sirven para guarecerse bajo sus húmedas sombras.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Paseos\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Las Cañas\n"
                + " \n"
                + "#telefono \n"
                + "-\n"
                + "\n"
                + "#web\n"
                + "www.xn--lascaas-8za.com/index.html\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/lascanas1.jpg\n"
                + "/descansoApp/baseDatos/lascanas2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Criolla de la Sociedad Nativista\n"
                + "\n"
                + "#detalles\n"
                + "Semana de Turismo, 9 días desde el primer sábado al último domingo. Lugar: Paraje La Balanza, Barrio Anglo, Fray Bentos. La fiesta comienza el primer sábado de la Semana de Turismo con un desfile de caballería guacha que recorre las calles de la ciudad de Fray Bentos, arribando al predio de la Socidad Nativista El Rincón, en Barrio Anglo. Allí se realizan jineteadas y espectáculos artísticos. Además hay payadas, peñas, feria con stands y venta de artesanías, plaza de comidas tradicionales y asado con cuero durante toda la semana.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Fiestas Populares\n"
                + "\n"
                + "#horario\n"
                + "Solo en semana de turismo.\n"
                + "\n"
                + "#ubicacion\n"
                + "Paraje La Balanza, Barrio Anglo, Fray Bentos\n"
                + " \n"
                + "#telefono \n"
                + "4562 2233\n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/semana-de-turismo\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/fiesta1.jpg\n"
                + "/descansoApp/baseDatos/fiesta2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Camping Las Cañas\n"
                + "\n"
                + "#detalles\n"
                + "El Balneario cuenta con una excelente zona de camping y picnic en una extensión de 60 hectáreas estando abierto todo el año, tiene buena infraestructura con caminos pavimentados, el suelo es mezcla de tierra y arena, y una muy buena sombra de árboles autóctonos.Tiene una buena cantidad de baterías de baños y duchas con agua caliente, lugar para lavar ropa y vajilla, lugar donde tirar la basura y recolección de residuos a diario, agua corriente y energía eléctrica siempre cerca, parrilleros, teléfonos públicos, proveedurías, entretenimientos, policlínica, paradores, paseo de artesanos y todo lo que el campamentista necesite para pasarla bien.\n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Camping\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Balneario Las Cañas \n"
                + "\n"
                + "#telefono \n"
                + "4562 2224 \n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/las-canias\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/campingl1.jpg\n"
                + "/descansoApp/baseDatos/campingl2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Plaza Hotel\n"
                + "\n"
                + "#detalles\n"
                + "El Plaza Hotel está ubicado frente a la plaza Constitución, en pleno centro de la ciudad y a escasos metros de la Intendencia.  Una dedicada atención al pasajero en todo momento y lugar. Disfrutará de un descanso seguro en un ambiente apacible y confortable. Capacidad para 56 pasajeros. La comodidad de estar cerca de todo. Amplio lobby ambientado con buen gusto y sobriedad.\n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Hotel\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "18 de julio y 25 de mayo\n"
                + "\n"
                + "#telefono \n"
                + "4562-2363 / 4562-3815\n"
                + "\n"
                + "#web\n"
                + "www.plazahotelfraybentos.com.uy\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/hotelp1.jpg\n"
                + "/descansoApp/baseDatos/hotelp2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Posada del Frayle Bentos\n"
                + "\n"
                + "#detalles\n"
                + "Casona ubicada en el centro histórico de la ciudad. Reciclada a nuevo perservando la influencia inglesa y oriental, este hotel ofrece 15 habitaciones amplias he iluminadas.El hotel además ofrece desayuno buffet, internet 24 hrs, sala de tv y lectura, verdes patios y piscinas.\n"
                + "\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Posada\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "25 de Mayo 3434\n"
                + "\n"
                + "#telefono \n"
                + "4562-8541 / 4562- 8542\n"
                + "\n"
                + "#web\n"
                + "www.posadadelfraylebentos.com.uy\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/posadaf1.jpg\n"
                + "/descansoApp/baseDatos/posadaf2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Camping Playa Ubici\n"
                + "\n"
                + "#detalles\n"
                + "Sobre la Ruta Puente- Puerto, distante 2 kilómetros de la ciudad de Fray bentos, se encuentra el acceso a la Playa Ubici. Sobre la costa del río Uruguay, es una buena playa que además cuenta con Parador y Moteles del Círculo Policial, así como zona de camping.Desde este estratégico lugar se disfruta de una vista privilegiada del Puente Internacional Gral. San Martín y de la Planta de Celulosa Botnia, a escasa distancia del lugar.\n"
                + "#tipo\n"
                + "alojamiento\n"
                + "\n"
                + "#categoria\n"
                + "Camping\n"
                + "\n"
                + "#horario\n"
                + "Las 24hs\n"
                + "\n"
                + "#ubicacion\n"
                + "Playa Ubici \n"
                + "\n"
                + "#telefono \n"
                + "598 4562 4915\n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/playa-ubici\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/campingp1.jpg\n"
                + "/descansoApp/baseDatos/campingp2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Confiteria El Paragua\n"
                + "\n"
                + "#detalles\n"
                + "Un lugar especial para el encuentro con amigos y para reunirse en familia, ofreciendo una variedad de platos: desayunos , almuerzos, comidas rapidas, pizzeria. Ubicado en el centro de la ciudad de Fray Bentos.\n"
                + "\n"
                + "\n"
                + "#tipo\n"
                + "estGastronomico\n"
                + "\n"
                + "#categoria\n"
                + "Restaurante\n"
                + "\n"
                + "#horario\n"
                + "Lun - Dom: 10:00-15:30 ---  19:00 - 00:30\n"
                + "\n"
                + "#ubicacion\n"
                + "18 de julio c/ brasil\n"
                + "\n"
                + "#telefono \n"
                + "4562 6165\n"
                + "\n"
                + "#web\n"
                + "www.facebook.com/confiteria.elparagua\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/restaurantp1.jpg\n"
                + "/descansoApp/baseDatos/restaurantp2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Teatro Miguel Young\n"
                + "\n"
                + "#detalles\n"
                + "El teatro está situado en la esquina Nord-Este de las calles Zorrilla de San Martín y 25 de Mayo.\n"
                + "\n"
                + "Se destaca por la belleza de sus líneas, esbeltas y macizas a la vez, por la pureza de sus materiales que evocan la opulencia de una época ya pasada.\n"
                + "Fue inaugurado el 4 de enero de 1913, el Dr. Juan Zorrilla de San Martín pronunció un discurso brillante, y recitó su obra máxima la \"Leyenda Patria\", continuando los actos con la presentación de Compañías Italianas de Operetas y primeras figuras del Teatro de Buenos Aires.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Teatro\n"
                + "\n"
                + "#horario\n"
                + "Ver en cartelera\n"
                + "\n"
                + "#ubicacion\n"
                + "Zorrilla entre 25 de mayo\n"
                + "\n"
                + "#telefono \n"
                + "4562 2567\n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/teatro-miguel-young\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/teatroy1.jpg\n"
                + "/descansoApp/baseDatos/teatroy2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Teatro De Verano\n"
                + "\n"
                + "#detalles\n"
                + "Ubicado en las barrancas costera de la ciudad sobre las costas del Río Uruguay, el parque fue construido aprovechando dichas barrancas de limo de 35 millones de años de antigüedad. En su centro se encuentra el Teatro de Verano Municipal, con capacidad para 4000 personas, realizado según las técnicas de los antiguos anfiteatros griegos, cuenta por debajo de su teatrón con canales por donde se escurren las aguas en sus graderías, y se mantienen allí parcialmente sirviendo de caja de resonancia para ayudar en su acústica.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Teatro\n"
                + "\n"
                + "#horario\n"
                + "Libre\n"
                + "\n"
                + "#ubicacion\n"
                + "Rambla Fray Bentos\n"
                + "\n"
                + "#telefono \n"
                + "-\n"
                + "\n"
                + "#web\n"
                + "www.rionegro.gub.uy/web/rio-negro/teatro-de-verano\n"
                + "\n"
                + "#precio\n"
                + "Gratis\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/teatrov1.jpg\n"
                + "/descansoApp/baseDatos/teatrov2.jpg\n"
                + "\n"
                + "#end\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "#nombre\n"
                + "Discoteca W Fray Bentos\n"
                + "\n"
                + "#detalles\n"
                + "Divertido lugar para salir con amigos y disfrutar la noche. Ubicado en el centro de Fray Bentos, W ofrece una variada forma de entretenimiento, con bandas en vivo y los mejores djs del uruguay. Un excelente lugar para salir con tus amigos y pasar una noche inolvidable. Se dispone de dos pisos, el primero donde se ubica el escenario y la pista bailable ademas de dos barras. El segundo, apto solamente para mayores de 18 incluyendo una barra. Además cada piso incluye un patio para fumadores.\n"
                + "\n"
                + "#tipo\n"
                + "actividad\n"
                + "\n"
                + "#categoria\n"
                + "Discoteca\n"
                + "\n"
                + "#horario\n"
                + "Sabados desde 23:30 hasta Domingo 8:00\n"
                + "\n"
                + "#ubicacion\n"
                + "Treinta y Tres entre 18 de julio y Zorrilla\n"
                + "\n"
                + "#telefono \n"
                + "4562 0816\n"
                + "\n"
                + "#web\n"
                + "https://www.facebook.com/wfraybentos.wfraybentos\n"
                + "\n"
                + "#precio\n"
                + "-\n"
                + "\n"
                + "#rutas\n"
                + "/descansoApp/baseDatos/discoteca1.jpg\n"
                + "/descansoApp/baseDatos/discoteca2.jpg\n"
                + "\n"
                ;

        return texto;
    }
}
